### ISSUE TITLE
[Bug] I am unable to install neofetch

### ISSUE THREAD

**Issue by dnkmmr69420** [leleliu008/ppkg#2]
[vm@fedora ~]$ ppkg install curl neofetch
==> to install neofetch brotli liblzma zlib libzstd perl openssl libnghttp2 curl  

=============== Installing neofetch ===============

=>> STEP 1 : view formula 
summary: Fast, highly customisable system info script
git-url: https://github.com/dylanaraps/neofetch.git
src-url: https://github.com/dylanaraps/neofetch/archive/7.1.0.tar.gz
src-sha: 58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7
license: MIT

binbstd: yes
install: |
    install_bins neofetch &&
    install_mans neofetch.1

🔔  if you want to have a better experience, I strongly recommend you to install bat on this machine. For more details, please visit website https://github.com/sharkdp/bat

=>> STEP 2 : load formula 

=>> STEP 3 : install depentent tools via uppm 
🔔  package [curl] already has been installed.
🔔  package [gtar] already has been installed.
🔔  package [gzip] already has been installed.

=>> STEP 4 : create relevant directories 

=>> STEP 5 : export relevant environment variables 
==> -DNDEBUG -std=c99 -o /var/home/vm/.ppkg/core/bin/proxy-cc /var/home/vm/.ppkg/core/bin/proxy-cc.c
/usr/local/bin/ppkg: line 111: eval: -D: invalid option
eval: usage: eval [arg ...]

**Comment by leleliu008** [comment]
your version is old, not the lastest version. It seems that you do not install the c compiler.

**Comment by leleliu008** [comment]
c compiler would be automatically installed when you run `ppkg setup` command

what's your system? could you give me your system infomation? run `ppkg env`

**Comment by dnkmmr69420** [comment]
its working now I needed to do `sudo dnf groupinstall "Development Tools"`
